import { ClerkProvider } from '@clerk/nextjs';
import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { connection } from 'next/server';
import { Suspense } from 'react';
import { extractRouterConfig } from 'uploadthing/server';

import '@/assets/styles/globals.css';

import { ourFileRouter } from './api/uploadthing/core';
import { ConfettiProvider } from '@/providers/confetti-provider';
import ToasterProvider from '@/providers/toaster-provider';

const geistSans = localFont({
	src: '../assets/fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: '../assets/fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	icons: [{ url: '/images/favicon.svg', href: '/images/favicon.svg' }],
};

async function UTSSR() {
	await connection();
	return <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />;
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
					<ConfettiProvider />
					<ToasterProvider />
					<Suspense>
						<UTSSR />
					</Suspense>{' '}
					{children}
				</body>
			</html>
		</ClerkProvider>
	);
}
